blank_issues_enabled: false
contact_links:
  - name: Translate Neo Feed
    url: https://hosted.weblate.org/engage/neo-feed/
    about: Help translate Neo Feed to your language on Weblate
  - name: Matrix Community
    url: https://matrix.to/#/#neo-launcher:matrix.org
    about: 'Join our Matrix community group!'
  - name: Telegram Community
    url: https://t.me/neo_launcher
    about: 'Join our Telegram community group!'
